

function myFunction() {
    var x = document.getElementById("myNumber");
    var currentVal = x.value;
    if(currentVal=="1"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="none"
        document.getElementById("para3").style.display="none"
        document.getElementById("para4").style.display="none"
        document.getElementById("para5").style.display="none"
        document.getElementById("para6").style.display="none"
        document.getElementById("para7").style.display="none"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }else if(currentVal=="2"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="none"
        document.getElementById("para4").style.display="none"
        document.getElementById("para5").style.display="none"
        document.getElementById("para6").style.display="none"
        document.getElementById("para7").style.display="none"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }
    else if(currentVal=="3"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="none"
        document.getElementById("para5").style.display="none"
        document.getElementById("para6").style.display="none"
        document.getElementById("para7").style.display="none"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }else if(currentVal=="4"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="block"
        document.getElementById("para5").style.display="none"
        document.getElementById("para6").style.display="none"
        document.getElementById("para7").style.display="none"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }else if(currentVal=="5"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="block"
        document.getElementById("para5").style.display="block"
        document.getElementById("para6").style.display="none"
        document.getElementById("para7").style.display="none"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }else if(currentVal=="6"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="block"
        document.getElementById("para5").style.display="block"
        document.getElementById("para6").style.display="block"
        document.getElementById("para7").style.display="none"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }
    else if(currentVal=="7"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="block"
        document.getElementById("para5").style.display="block"
        document.getElementById("para6").style.display="block"
        document.getElementById("para7").style.display="block"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }
    else if(currentVal=="7"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="block"
        document.getElementById("para5").style.display="block"
        document.getElementById("para6").style.display="block"
        document.getElementById("para7").style.display="block"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }
    else if(currentVal=="8"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="block"
        document.getElementById("para5").style.display="block"
        document.getElementById("para6").style.display="block"
        document.getElementById("para7").style.display="block"
        document.getElementById("para8").style.display="block"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }else if(currentVal=="9"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="block"
        document.getElementById("para5").style.display="block"
        document.getElementById("para6").style.display="block"
        document.getElementById("para7").style.display="block"
        document.getElementById("para8").style.display="block"
        document.getElementById("para9").style.display="block"
        document.getElementById("para10").style.display="none"
    }
    else if(currentVal=="0"){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="none"
        document.getElementById("para3").style.display="none"
        document.getElementById("para4").style.display="none"
        document.getElementById("para5").style.display="none"
        document.getElementById("para6").style.display="none"
        document.getElementById("para7").style.display="none"
        document.getElementById("para8").style.display="none"
        document.getElementById("para9").style.display="none"
        document.getElementById("para10").style.display="none"
    }
    else if(currentVal>=10){
        document.getElementById("para1").style.display="block"
        document.getElementById("para2").style.display="block"
        document.getElementById("para3").style.display="block"
        document.getElementById("para4").style.display="block"
        document.getElementById("para5").style.display="block"
        document.getElementById("para6").style.display="block"
        document.getElementById("para7").style.display="block"
        document.getElementById("para8").style.display="block"
        document.getElementById("para9").style.display="block"
        document.getElementById("para10").style.display="block"
    }
   
  }